apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: thanos-metrics-reader 
  namespace:  custom-metric-autoscaler-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: thanos-metrics-reader
subjects:
- kind: ServiceAccount
  name: thanos 
  namespace: custom-metric-autoscaler-demo
